weave_launch_peers: "
{%- if inventory_hostname == groups[weave_server_group][0] -%}
{%- else -%}
{%- for host in groups[weave_server_group] -%}
{%- if host != inventory_hostname -%}
{{ hostvars[host].ansible_ssh_host }}
{%- endif -%}
{%- endfor -%}
{%- endif -%}"

weave_proxy_args: '--rewrite-inspect'
weave_router_args: ''
weave_version: 1.7.2
scope_enabled: true
weave_scope_peers: ''
proxy_env: 
  none: none